### ISSUE TITLE
[BUG] Issues with deploying the bot via docker

### ISSUE THREAD

**Issue by EverythingSuckz** [userbotindo/Anjani#288]
### Describe the Bug

I tried to deploy the bot on my VPS using docker and I'm getting the `sqlite3.IntegrityError: UNIQUE constraint failed: peers.id` error.

### Step to Reproduce

```sh

git clone https://github.com/userbotindo/Anjani
cd Anjani
sudo docker build . -t anjani
sudo docker run --restart unless-stopped --name anjaniBot anjani

```

### Expected Behavior

The bot was supposed to be running normally.

### Logs (if any)

```Shell
❯ sudo docker run --restart unless-stopped --name anjaniBot anjani
Skipping virtualenv creation, as specified in config file.
  INFO      |  launch           |  Running on Python 3.9.16
  INFO      |  launch           |  Loading code
  INFO      |  launch           |  Using uvloop event loop
  INFO      |  launch           |  Initializing bot
  INFO      |  bot              |  Starting
  INFO      |  bot              |  Loading session from database
  INFO      |  bot              |  Loading plugins
  INFO      |  bot              |  Loading plugin 'Admins' (Admins) from 'anjani/plugins/admins.py'
  INFO      |  bot              |  Loading plugin 'Backups' (Backups) from 'anjani/plugins/backups.py'
  INFO      |  bot              |  Loading plugin 'Debug' (Debug) from 'anjani/plugins/debug.py'
  INFO      |  bot              |  Loading plugin 'Federations' (Federation) from 'anjani/plugins/federation.py'
  INFO      |  bot              |  Loading plugin 'Filters' (Filters) from 'anjani/plugins/filters.py'
  INFO      |  bot              |  Loading plugin 'Language' (Language) from 'anjani/plugins/language.py'
  INFO      |  bot              |  Loading plugin 'Lockings' (Lockings) from 'anjani/plugins/lockings.py'
  INFO      |  bot              |  Loading plugin 'Main' (Main) from 'anjani/plugins/main.py'
  INFO      |  bot              |  Loading plugin 'Miscs' (Misc) from 'anjani/plugins/misc.py'
  INFO      |  bot              |  Loading plugin 'Muting' (Muting) from 'anjani/plugins/muting.py'
  INFO      |  bot              |  Loading plugin 'Notes' (Notes) from 'anjani/plugins/notes.py'
  INFO      |  bot              |  Loading plugin 'Purges' (Purges) from 'anjani/plugins/purge.py'
  INFO      |  bot              |  Loading plugin 'Reporting' (Reporting) from 'anjani/plugins/reporting.py'
  INFO      |  bot              |  Loading plugin 'Restriction' (Restrictions) from 'anjani/plugins/restriction.py'
  INFO      |  bot              |  Loading plugin 'Rules' (Rules) from 'anjani/plugins/rules.py'
  INFO      |  bot              |  Loading plugin 'SpamShield' (SpamShield) from 'anjani/plugins/spam_shield.py'
  INFO      |  bot              |  Loading plugin 'Staff Tools' (Staff) from 'anjani/plugins/staff_tools.py'
  INFO      |  bot              |  Loading plugin 'Stats' (PluginStats) from 'anjani/plugins/stats.py'
  INFO      |  bot              |  Loading plugin 'Users' (Users) from 'anjani/plugins/users.py'
  INFO      |  bot              |  Loading plugin 'Greetings' (Greeting) from 'anjani/plugins/welcome.py'
  INFO      |  bot              |  All plugins loaded.
  INFO      |  bot              |  Stopping
  ERROR     |  bot              |  Error dispatching event 'stop' on Main.on_stop with data
Traceback (most recent call last):
  File "/anjani/anjani/core/event_dispatcher.py", line 188, in dispatch_event
    result = await lst.func(*args, **kwargs)
  File "/anjani/anjani/plugins/main.py", line 102, in on_stop
    data = await self.bot.client.invoke(GetState())
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/invoke.py", line 71, in invoke
    raise ConnectionError("Client has not been started yet")
anjani.error.EventDispatchError: raised from ConnectionError: Client has not been started yet
  INFO      |  bot              |  Running post-stop hooks
  ERROR     |  asyncio          |  Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.9/site-packages/aiorun.py:227> exception=IntegrityError('UNIQUE constraint failed: peers.id')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/anjani/anjani/core/anjani_bot.py", line 65, in init_and_run
    await anjani.run()
  File "/anjani/anjani/core/telegram_bot.py", line 248, in run
    await self.start()
  File "/anjani/anjani/core/telegram_bot.py", line 139, in start
    await self.client.start()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 616, in load_session
    await self.storage.open()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/storage/file_storage.py", line 66, in open
    self.conn.execute("VACUUM")
sqlite3.IntegrityError: UNIQUE constraint failed: peers.id
```

**Comment by MrMissx** [comment]
I can't reproduce this behavior. Seems like it's a problem on your session file.
Try to delete the `SESSION` collection on the MongoDB.

**Comment by EverythingSuckz** [comment]
Oh yeah, never knew mongo had a copy of the corrupt session file. The issue was resolved. Thank you.
